#ifndef MANDEL_CONST_H
#define MANDEL_CONST_H

#define MANDEL_OK		0
#define MANDEL_ERR_STRANGE	-1
#define MANDEL_ERR_ARGCOUNT	1
#define MANDEL_ERR_XMINMAX	2
#define MANDEL_ERR_YMINMAX	3
#define MANDEL_ERR_VIDEO_LOCKSURFACE	4
#define MANDEL_ERR_VIDEO_INITSDL	5
#define MANDEL_ERR_VIDEO_GETINFO	6
#define MANDEL_ERR_VIDEO_SETMODE	7
#define MANDEL_ERR_VIDEO_PIXELFORMAT	8
#define MANDEL_ERR_VIDEO_MANYBYTECOLORS	9
#define MANDEL_ERR_VIDEO_DRIVERNAME	10
#define MANDEL_ERR_PNG	11


#define MANDEL_DEFAULT_XMIN	-2.0
#define MANDEL_DEFAULT_XMAX	2.0
#define MANDEL_DEFAULT_YMIN	-2.0
#define MANDEL_DEFAULT_YMAX	2.0

#define MANDEL_EXCEED		10000
#define MANDEL_STEPS		255.0


#endif
